// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3VqW7Huupb67nhQ_dn-vRLfgd-CZ44A',
    appId: '1:822390441854:web:14ed1b9cac09eb1b64152f',
    messagingSenderId: '822390441854',
    projectId: 'fruit-app-9bc87',
    authDomain: 'fruit-app-9bc87.firebaseapp.com',
    storageBucket: 'fruit-app-9bc87.firebasestorage.app',
    measurementId: 'G-FPFZ354ZL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFrbSnq5KIGRcwLw6DS2GiVW_rSFLUV_0',
    appId: '1:822390441854:android:38ad608f045c943764152f',
    messagingSenderId: '822390441854',
    projectId: 'fruit-app-9bc87',
    storageBucket: 'fruit-app-9bc87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsA_aq-89R_hOJ4520TIskZhZEG7FZXTA',
    appId: '1:822390441854:ios:bde49a964edf636864152f',
    messagingSenderId: '822390441854',
    projectId: 'fruit-app-9bc87',
    storageBucket: 'fruit-app-9bc87.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsA_aq-89R_hOJ4520TIskZhZEG7FZXTA',
    appId: '1:822390441854:ios:bde49a964edf636864152f',
    messagingSenderId: '822390441854',
    projectId: 'fruit-app-9bc87',
    storageBucket: 'fruit-app-9bc87.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn3VqW7Huupb67nhQ_dn-vRLfgd-CZ44A',
    appId: '1:822390441854:web:7fda0d1c087a5f7264152f',
    messagingSenderId: '822390441854',
    projectId: 'fruit-app-9bc87',
    authDomain: 'fruit-app-9bc87.firebaseapp.com',
    storageBucket: 'fruit-app-9bc87.firebasestorage.app',
    measurementId: 'G-R1XNRTVF9K',
  );
}
